name: Upload Docker Image to ECR

on:
  push:
    branches: [ main, develop ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set STAGE environment variable
        run: echo "STAGE=$([[ '${{ github.ref }}' == 'refs/heads/main' ]] && echo 'prod' || echo 'dev')" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: ${{ secrets.AWS_REGION }}
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Build, tag, and push Docker image to Amazon ECR
        run: |
          IMAGE_TAG=$([[ "$STAGE" == 'prod' ]] && echo 'latest' || echo 'dev')
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY=${{ secrets.AWS_ECR_REPOSITORY }}
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
